<?php

namespace PharmaQuiz\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DefinitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefinitionRepository extends EntityRepository
{
}
