<?php

namespace PharmaQuiz\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuizQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizQuestionRepository extends EntityRepository
{
    public function findRandom($limit)
    {
        $query = $this->createQueryBuilder('qq')
            ->addSelect('RAND() as HIDDEN rand')
            ->where('qq.published = 1')
            ->orderBy('rand')
            ->setMaxResults($limit)
            ->getQuery();

        return $query->getResult();
    }

    public function findRandomByCategory($id, $limit)
    {
        $query = $this->createQueryBuilder('qq')
            ->addSelect('RAND() as HIDDEN rand')
            ->where('qq.categoryId = :categoryId')
            ->andWhere('qq.published = 1')
            ->orderBy('rand')
            ->setMaxResults($limit)
            ->setParameter('categoryId', $id)
            ->getQuery();

        return $query->getResult();
    }
}
