<?php

namespace PharmaQuiz\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuizAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizAnswerRepository extends EntityRepository
{
}
